import turtle
turtle.Screen().bgcolor("blue")
sc=turtle.Screen()
sc.setup(400,300)
board=turtle.Turtle()
board.fillcolor("orange")
board.begin_fill()
for i in range(4):
    board.forward(50)
    board.left(90)
board.end_fill()
board.penup()
board.left(90)
board.forward(50)
board.right(45)
board.pendown()
board.forward(40)
board.right(96)
board.forward(40)
board.hideturtle()
turtle.done()
